# Generated by Django 4.0.3 on 2022-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_alter_post_options_post_daromadi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('daromadi', models.IntegerField(max_length=2)),
            ],
            options={
                'verbose_name': 'Post1',
                'verbose_name_plural': 'Posts1',
            },
        ),
    ]
