# Generated by Django 4.0.3 on 2022-04-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_post2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post2',
            options={'verbose_name': 'Post2', 'verbose_name_plural': 'Posts2'},
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='daromadi',
            new_name='rating',
        ),
    ]
